### ISSUE TITLE
v15.0 sdk is not published yet but It is mandatory to use

### ISSUE THREAD

**Issue by roberjc** [facebook/facebook-java-business-sdk#406] opened 2022-10-19 11:07 UTC
### Which SDK version are you using?
The latest version available in maven repository (v14.0): https://mvnrepository.com/artifact/com.facebook.business.sdk/facebook-java-business-sdk/14.0.0

### What's the issue?
We are unable to use Graph API with java sdk and develop Facebook Ads on our product because the v15.0 sdk has not been published yet and it is mandatory to use it.

#### Observed Results:

  * What happened?  This could be a description, log output, etc.
`{"error":{"message":"(#xxxx) You are calling a deprecated version of the Ads API. Please update to the latest version: v15.0.","type":"OAuthException","code":xxxx,"fbtrace_id":"xxxxxxxxxxxxxxxxxxxxxxx"}}`
As v14.0 sdk shows, we are calling a deprecated version of the Ads API and It recomends to update to the latest version: v15.0

#### Expected Results:

  * What did you expect to happen?
Publish facebook-java-business-sdk v15.0 to maven repository

**Comment by DirkRusche** [comment] 2022-10-20 18:36
Duplicate of https://github.com/facebook/facebook-java-business-sdk/issues/400

**Closed** 2022-11-09 10:53 UTC
